### ISSUE TITLE
NoSuchMethodError when opening any pyxl file in PyCharm 2016.1

### ISSUE THREAD

**Issue by JFury** [christoffer/pycharm-pyxl#22]
`
com.jetbrains.python.psi.PyImportElement.getElementNamed(Ljava/lang/String;)Lcom/intellij/psi/PsiElement;
java.lang.NoSuchMethodError: com.jetbrains.python.psi.PyImportElement.getElementNamed(Ljava/lang/String;)Lcom/intellij/psi/PsiElement;
	at com.christofferklang.pyxl.psi.PythonClassReference.getImportedPyxlHtmlModuleElement(PythonClassReference.java:226)
	at com.christofferklang.pyxl.psi.PythonClassReference.getQualifier(PythonClassReference.java:154)
	at com.jetbrains.python.codeInsight.PyInjectionUtil.a(PyInjectionUtil.java:126)
	at com.jetbrains.python.codeInsight.PyInjectionUtil.a(PyInjectionUtil.java:111)
	at com.jetbrains.python.codeInsight.PyInjectionUtil.getLargestStringLiteral(PyInjectionUtil.java:75)
	at com.jetbrains.python.codeInsight.regexp.PythonRegexpInjector.getLanguagesToInject(PythonRegexpInjector.java:75)
	at com.intellij.psi.impl.source.tree.injected.InjectedPsiCachedValueProvider$MyInjProcessor.process(InjectedPsiCachedValueProvider.java:82)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageManagerImpl.processInPlaceInjectorsFor(InjectedLanguageManagerImpl.java:474)
	at com.intellij.psi.impl.source.tree.injected.InjectedPsiCachedValueProvider.doCompute(InjectedPsiCachedValueProvider.java:62)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtil.a(InjectedLanguageUtil.java:316)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtil.enumerate(InjectedLanguageUtil.java:145)
	at com.intellij.codeInsight.daemon.impl.InjectedGeneralHighlightingPass$2.process(InjectedGeneralHighlightingPass.java:191)
	at com.intellij.codeInsight.daemon.impl.InjectedGeneralHighlightingPass$2.process(InjectedGeneralHighlightingPass.java:186)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:128)
	at com.intellij.concurrency.ApplierCompleter.access$000(ApplierCompleter.java:44)
	at com.intellij.concurrency.ApplierCompleter$1.run(ApplierCompleter.java:91)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1178)
	at com.intellij.concurrency.ApplierCompleter$2.run(ApplierCompleter.java:100)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:112)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:88)
	at jsr166e.CountedCompleter.exec(CountedCompleter.java:684)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)
`

**Comment by lihaoyi** [comment]
I'm getting this too

```
com.jetbrains.python.psi.PyImportElement.getElementNamed(Ljava/lang/String;)Lcom/intellij/psi/PsiElement;
java.lang.NoSuchMethodError: com.jetbrains.python.psi.PyImportElement.getElementNamed(Ljava/lang/String;)Lcom/intellij/psi/PsiElement;
	at com.christofferklang.pyxl.psi.PythonClassReference.getImportedPyxlHtmlModuleElement(PythonClassReference.java:226)
	at com.christofferklang.pyxl.psi.PythonClassReference.getQualifier(PythonClassReference.java:154)
	at com.jetbrains.python.codeInsight.PyInjectionUtil.getFormatCallQualifier(PyInjectionUtil.java:126)
	at com.jetbrains.python.codeInsight.PyInjectionUtil.isStringLiteralPart(PyInjectionUtil.java:111)
	at com.jetbrains.python.codeInsight.PyInjectionUtil.getLargestStringLiteral(PyInjectionUtil.java:75)
	at com.jetbrains.python.codeInsight.regexp.PythonRegexpInjector.getLanguagesToInject(PythonRegexpInjector.java:75)
	at com.intellij.psi.impl.source.tree.injected.InjectedPsiCachedValueProvider$MyInjProcessor.process(InjectedPsiCachedValueProvider.java:82)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageManagerImpl.processInPlaceInjectorsFor(InjectedLanguageManagerImpl.java:474)
	at com.intellij.psi.impl.source.tree.injected.InjectedPsiCachedValueProvider.doCompute(InjectedPsiCachedValueProvider.java:62)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtil.a(InjectedLanguageUtil.java:316)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtil.enumerate(InjectedLanguageUtil.java:145)
	at com.intellij.codeInsight.daemon.impl.InjectedGeneralHighlightingPass$2.process(InjectedGeneralHighlightingPass.java:191)
	at com.intellij.codeInsight.daemon.impl.InjectedGeneralHighlightingPass$2.process(InjectedGeneralHighlightingPass.java:186)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:128)
	at com.intellij.concurrency.ApplierCompleter.access$000(ApplierCompleter.java:44)
	at com.intellij.concurrency.ApplierCompleter$1.run(ApplierCompleter.java:91)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1178)
	at com.intellij.concurrency.ApplierCompleter$2.run(ApplierCompleter.java:100)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:112)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:88)
	at jsr166e.CountedCompleter.exec(CountedCompleter.java:684)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)



java.lang.NoSuchMethodError: com.jetbrains.python.psi.PyImportElement.getElementNamed(Ljava/lang/String;)Lcom/intellij/psi/PsiElement;
	at com.christofferklang.pyxl.psi.PythonClassReference.getImportedPyxlHtmlModuleElement(PythonClassReference.java:226)
	at com.christofferklang.pyxl.psi.PythonClassReference.getQualifier(PythonClassReference.java:154)
	at com.jetbrains.python.codeInsight.PyInjectionUtil.getFormatCallQualifier(PyInjectionUtil.java:126)
	at com.jetbrains.python.codeInsight.PyInjectionUtil.isStringLiteralPart(PyInjectionUtil.java:111)
	at com.jetbrains.python.codeInsight.PyInjectionUtil.getLargestStringLiteral(PyInjectionUtil.java:75)
	at com.jetbrains.python.codeInsight.regexp.PythonRegexpInjector.getLanguagesToInject(PythonRegexpInjector.java:75)
	at com.intellij.psi.impl.source.tree.injected.InjectedPsiCachedValueProvider$MyInjProcessor.process(InjectedPsiCachedValueProvider.java:82)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageManagerImpl.processInPlaceInjectorsFor(InjectedLanguageManagerImpl.java:474)
	at com.intellij.psi.impl.source.tree.injected.InjectedPsiCachedValueProvider.doCompute(InjectedPsiCachedValueProvider.java:62)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtil.a(InjectedLanguageUtil.java:316)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtil.enumerate(InjectedLanguageUtil.java:145)
	at com.intellij.codeInsight.daemon.impl.InjectedGeneralHighlightingPass$2.process(InjectedGeneralHighlightingPass.java:191)
	at com.intellij.codeInsight.daemon.impl.InjectedGeneralHighlightingPass$2.process(InjectedGeneralHighlightingPass.java:186)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:128)
	at com.intellij.concurrency.ApplierCompleter.access$000(ApplierCompleter.java:44)
	at com.intellij.concurrency.ApplierCompleter$1.run(ApplierCompleter.java:91)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1178)
	at com.intellij.concurrency.ApplierCompleter$2.run(ApplierCompleter.java:100)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:112)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:88)
	at jsr166e.CountedCompleter.exec(CountedCompleter.java:684)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)

```
